--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/InfectedGM
branches:
- master
projects:
  InfectedGM:
    path: ""
    libs:
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
    - src: thebigsmilexd/gameapi/gameapi
      version: ^4.0.7
    - src: thebigsmilexd/skinapi/skinapi
      version: ^0.3.0
...
